lock-time: 3 #in seconds
delay-end-duel-after-player-kill: 20 #in seconds
invite-timeout: 120 #in seconds

arena-regeneration:
  enabled: true # if set true, deletes blocks that is placed by players, after duel game.
  remove-entities: true #removes DROPPED ITEMS and PROJECTILES that are in arena region.
# if you need more complex arena regeneration we recommended rollbackcore: https://www.spigotmc.org/resources/rollbackcore-1-4-7-1-17-1.18517/

# If set true, MasterDuels will changes Bukkit world configurations of all
# worlds of arenas. Thats includes game rules of the worlds.
optimize-duel-worlds: false

executable-commands-by-player:
  BATTLE:
    #- this_command_is_executable_in_battle
  ROUND_STARTING:
    #- this_command_is_executable_before_game_start
  GAME_ENDING:
    #- this_command_is_executable_after_victim_dead
    #- this_command_is_executable_after_victim_dead_too
  #empty lists means all commands should be blocked.

scoreboards: #Requires TitleManager plugin
  enabled: true
  BATTLE:
    title: '&e&lDUELS'
    live-opponent-format: '&a{name} &c{health}❤'
    dead-opponent-format: '&a{name} &cDEAD'
    lines:
      - '&fRound: &e#{round}'
      - '&fMap: &e{map}'
      - ''
      - '&fRemaining Time:'
      - ' &a{timer}'
      - ''
      - '{+opponents}'
      - ''
      - '&ewww.yourserver.net'
  ROUND_STARTING:
    title: '&e&lDUELS'
    live-opponent-format: '&a{name} &c{health}❤'
    dead-opponent-format: '&a{name} &cDEAD'
    lines:
      - '&fRound: &e#{round}'
      - '&fMap: &e{map}'
      - ''
      - '&fStarting: &a{timer}'
      - ''
      - '&ewww.yourserver.net'
  GAME_ENDING:
    title: '&e&lDUEL HAS ENDED'
    live-opponent-format: '&a{name} &c{health}❤'
    dead-opponent-format: '&a{name} &cDEAD'
    lines:
      - '&fRound: &e#{round}'
      - '&fMap: &e{map}'
      - ''
      - '&fArena Closing: '
      - '&c{timer}'
      - ''
      - '{+opponents}'
      - ''
      - '&ewww.yourserver.net'
titles:
  ROUND_STARTING:
    title: '&c&lGAME STARTING' # also, you can use {round} and {remaining-time-timer} placeholders
    subtitle: '&e{remaining-time-time}'
    fadein: 5 #in ticks
    stay: 20 #in ticks
    fadeout: 3 #in ticks
  SPECTATOR_JOIN:
    title: ''
    subtitle: '&7You are spectator now.'
    fadein: 20
    stay: 10
    fadeout: 20
  SPECTATOR_LEFT:
    title: ''
    subtitle: '&7You are no longer spectator.'
    fadein: 20
    stay: 10
    fadeout: 20
bossbars: #Requires TAB plugin
  enabled: true
  in-battle: 'Remaining Time: {time}' #also, you can use {timer} placeholder
  arena-closing: 'Arena Closing in: {time}'
