game-starting-lock-time: 3 #in seconds
delay-end-duel-after-player-kill: 20 #in seconds
invite-timeout: 120 #in seconds

arena-regeneration:
  enabled: true # if set true, deletes blocks that is placed by players, after duel game.
  remove-entities: true #removes DROPPED ITEMS and PROJECTILES that are in arena region.
  # liquids can not be deleted instantly, by smart arena regeneration.
  # MasterDuels does not follows liquid flows because this method is laggy.
  # if set false, liquids will deleted but naturally.
  use-full-scan-for-liquids: true

# if you need more complex arena regeneration we recommend rollbackcore: https://www.spigotmc.org/resources/rollbackcore-1-4-7-1-17-1.18517/

# if set true, MasterDuels will changes Bukkit world configurations of all
# worlds of arenas. Thats includes game rules of the worlds. We recommend this, if your duel arenas are in different world.
optimize-duel-worlds: false

# if set true, MasterDuels will not reset and backup inventory. (so this is means disabling kits)
# also, when a player die in duel, their items will drops. Do not change this option during server working.
use-player-inventories: false

# SERVER_WIDE - Send game end message to all players in the server
# SPECTATORS_AND_MEMBERS - Send game end message to all players in duel game
# DISABLED - Send game end message to nobody
game-end-broadcast-mode: 'SERVER_WIDE'

executable-commands-by-player:
  BATTLE:
    #- this_command_is_executable_in_battle
  ROUND_STARTING:
    #- this_command_is_executable_before_game_start
  GAME_ENDING:
    #- this_command_is_executable_after_victim_dead
    #- this_command_is_executable_after_victim_dead_too
  #empty lists means all commands should be blocked.



#{timer} = 13:59
#{time} = 13 minutes 59 seconds
#You can translate time format from message.yml time-format
scoreboards: #Requires TitleManager plugin
  enabled: true
  BATTLE:
    title: '&e&lDUELS'
    live-opponent-format: '&a{name} &c{health}❤'
    dead-opponent-format: '&a{name} &cDEAD'
    lines:
      - '&fRound: &e#{round}'
      - '&fMap: &e{map}'
      - ''
      - '&fRemaining Time:'
      - ' &a{timer}'
      - ''
      - '{+opponents}' # placeholder that is starts with '+', will clone as line for each opponent of player
      - ''
      - '&ewww.yourserver.net'
  ROUND_STARTING:
    title: '&e&lDUELS'
    live-opponent-format: '&a{name} &c{health}❤'
    dead-opponent-format: '&a{name} &cDEAD'
    lines:
      - '&fRound: &e#{round}'
      - '&fMap: &e{map}'
      - ''
      - '&fStarting: &a{timer}'
      - ''
      - '&ewww.yourserver.net'
  GAME_ENDING:
    title: '&e&lDUELS'
    live-opponent-format: '&a{name} &c{health}❤'
    dead-opponent-format: '&a{name} &cDEAD'
    lines:
      - '&fRound: &e#{round}'
      - '&fMap: &e{map}'
      - ''
      - '&fArena Closing: '
      - '&c{timer}'
      - ''
      - '{+opponents}'
      - ''
      - '&ewww.yourserver.net'
titles:
  ROUND_STARTING:
    title: '&c&lGAME STARTING' # also, you can use {round} and {remaining-time-timer} placeholders
    subtitle: '&e{remaining-time-time}'
    fadein: 5 #in ticks
    stay: 20 #in ticks
    fadeout: 3 #in ticks
  SPECTATOR_JOIN:
    title: ''
    subtitle: '&7You are spectator now.'
    fadein: 20
    stay: 10
    fadeout: 20
  SPECTATOR_LEFT:
    title: ''
    subtitle: '&7You are no longer spectator.'
    fadein: 20
    stay: 10
    fadeout: 20
bossbars: #Requires TAB plugin
  enabled: true
  in-battle: 'Remaining Time: {time}' #also, you can use {timer} placeholder
  arena-closing: 'Arena Closing in: {time}'
game-history:
  max-amount-of-histories-in-storage: 50
  cache-refresh: 1200 #in ticks
  gui:
    title: 'Duel History'
    solo-games-icon:
      material-type: PAPER
      description:
        - '&dGame Duration: &7{time}' # name of icon
        - ''
        - '&a{winner} &8⚔ &c{loser}'
        - ''
        - '&8Game played at: {played-date}'
    non-solo-games-icon:
      winners-format: ' &a{winner}!'
      losers-format: ' &c{loser}'
      material-type: PAPER
      description:
        - '&dGame Duration: &7{time}' # name of icon
        - ''
        - '&aWinners:'
        - ' {+winners}'
        - ''
        - '&cLosers:'
        - ' {+losers}'
        - ''
        - '&8Game played at: {played-date}'
