#
# Official wiki: https://mrobliviate.gitbook.io/masterduels-wiki-1/
# Developer Contact: https://www.spigotmc.org/conversations/add?to=_Obliviate_
#
# MasterDuels coded by Mr_Obliviate
#

game-starting-lock-time: 3 #in seconds
delay-end-duel-after-player-kill: 20 #in seconds
invite-timeout: 120 #in seconds

arena-regeneration:
  # SMART - removes only placed blocks, liquids and formed blocks(blocks creating when lava touched to water)
  # ROLLBACKCORE (COMING SOON) - regenerates all blocks in arena region (https://www.spigotmc.org/resources/rollbackcore-1-4-7-1-17-1.18517/)
  # SLIMEWORLD (COMING SOON) - regenerates world completely (https://www.spigotmc.org/resources/advanced-slimeworldmanager.87209/)
  regenerate-mode: SMART
  remove-entities: true #removes DROPPED ITEMS and PROJECTILES that are in arena region.

# if set true, players can break only placed blocks by a player (and formed blocks).
prevent-break-non-placed-blocks: true

# if set true, teleports player to arena area(1. team's 1. position) when they break/place block
# to out of arena cuboid. Do not set it true if you didn't set arena cuboids correctly.
teleport-back-when-arena-cuboid-violated: false

# if set true, MasterDuels will changes Bukkit world configurations of all
# worlds of arenas. Thats includes game rules of the worlds. We recommend this,
# if your duel arenas are in different world from another worlds you're using for another thing.
optimize-duel-worlds: false

# if set true, MasterDuels will not reset and backup inventory. (so this is means disabling kits)
# also, when a player die in duel, their items will drops. Do not change this option during server working.
use-player-inventories: false

#if set true, players can bet for their duel games.
#needs Vault
enable-bets: true

# SERVER_WIDE - Send game end message to all players in the server
# SPECTATORS_AND_MEMBERS - Send game end message to all players in duel game
# DISABLED - Send game end message to nobody
game-end-broadcast-mode: 'SERVER_WIDE'

top:
  top-wins:
    calculation-limit: 10

executable-commands-by-player:
  BATTLE:
  #- this_command_is_executable_in_battle
  ROUND_STARTING:
  #- this_command_is_executable_before_game_start
  GAME_ENDING:
  #- this_command_is_executable_after_victim_dead
  #- this_command_is_executable_after_victim_dead_too
  #empty lists means all commands should be blocked.

#{timer} = 13:59
#{time} = 13 minutes 59 seconds
#You can translate time format from message.yml time-format
scoreboards: #Requires TitleManager plugin
  enabled: true
  BATTLE:
    title: '&e&lDUELS'
    live-opponent-format: '&a{name} &c{health}❤'
    dead-opponent-format: '&a{name} &cDEAD'
    lines:
      - '&fRound: &e#{round}'
      - '&fMap: &e{map}'
      - ''
      - '&fRemaining Time:'
      - ' &a{timer}'
      - ''
      - '{+opponents}' # placeholder that is starts with '+', will clone as line for each opponent of player
      - ''
      - '&ewww.yourserver.net'
  ROUND_STARTING:
    title: '&e&lDUELS'
    live-opponent-format: '&a{name} &c{health}❤'
    dead-opponent-format: '&a{name} &cDEAD'
    lines:
      - '&fRound: &e#{round}'
      - '&fMap: &e{map}'
      - ''
      - '&fStarting: &a{timer}'
      - ''
      - '&ewww.yourserver.net'
  GAME_ENDING:
    title: '&e&lDUELS'
    live-opponent-format: '&a{name} &c{health}❤'
    dead-opponent-format: '&a{name} &cDEAD'
    lines:
      - '&fRound: &e#{round}'
      - '&fMap: &e{map}'
      - ''
      - '&fArena Closing: '
      - '&c{timer}'
      - ''
      - '{+opponents}'
      - ''
      - '&ewww.yourserver.net'
titles:
  ROUND_STARTING:
    title: '&c&lGAME STARTING' # also, you can use {round} and {remaining-time-timer} placeholders
    subtitle: '&e{remaining-time-time}'
    fadein: 5 #in ticks
    stay: 20 #in ticks
    fadeout: 3 #in ticks
  SPECTATOR_JOIN:
    title: ''
    subtitle: '&7You are spectator now.'
    fadein: 20
    stay: 10
    fadeout: 20
  SPECTATOR_LEFT:
    title: ''
    subtitle: '&7You are no longer spectator.'
    fadein: 20
    stay: 10
    fadeout: 20
bossbars: #Requires TAB plugin
  enabled: true
  in-battle: 'Remaining Time: {time}' #also, you can use {timer} placeholder
  arena-closing: 'Arena Closing in: {time}'
game-history:
  max-amount-of-histories-in-storage: 50
  cache-refresh: 1200 #in ticks
  gui:
    title: 'Duel History'
    solo-games-icon:
      material-type: PAPER
      description:
        - '&dGame Duration: &7{time}' # name of icon
        - ''
        - '&a{winner} &8⚔ &c{loser}'
        - ''
        - '&8Game played at: {played-date}'
    non-solo-games-icon:
      winners-format: ' &a{winner}!'
      losers-format: ' &c{loser}'
      material-type: PAPER
      description:
        - '&dGame Duration: &7{time}' # name of icon
        - ''
        - '&aWinners:'
        - ' {+winners}'
        - ''
        - '&cLosers:'
        - ' {+losers}'
        - ''
        - '&8Game played at: {played-date}'
duel-arenas-gui:
  enabled: true
  #You need 'masterduels.see-non-playing-games' permission to see 'disabled' and 'empty' arenas.
  title: 'Duel Arenas'
  size: 6
  page-slots: 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53
  icons:
    STARTING:
      material: YELLOW_WOOL
      display-name: '&dArena: #{arena}'
      lore:
        - ''
        - '&7State: &eStarting...'
        - '&7Players: &b{players}'
        - '&7Mode: &b{mode}'
        - ''
        - '&eClick to spectate game!'
    PLAYING:
      material: RED_WOOL
      display-name: '&dArena: #{arena}'
      lore:
        - ''
        - '&7State: &cPlaying'
        - '&7Players: &b{players}'
        - '&7Mode: &b{mode}'
        - ''
        - '&eClick to spectate game!'
    ENDING:
      material: YELLOW_WOOL
      display-name: '&dArena: #{arena}'
      lore:
        - ''
        - '&7State: &eEnding'
        - '&7Players: &b{players}'
        - '&7Mode: &b{mode}'
        - ''
        - '&eClick to spectate game!'
    EMPTY:
      material: LIME_WOOL
      display-name: '&dArena: #{arena}'
      lore:
        - ''
        - '&7State: &aAvailable'
        - '&7Map: &9{map}'
        - ''
    DISABLED:
      material: REDSTONE_BLOCK
      display-name: '&dArena: #{arena}'
      lore:
        - '&cThis arena currently'
        - '&cdisabled by administrators.'
        - ''
    UNKNOWN:
      material: BEDROCK
      display-name: '&dArena: #{arena}'
      lore:
        - ''
        - '&4Error'
        - ''
duel-creator:
  gui:
    title: 'Duel Creator {mode} &c&lBETA'
    size: 5
    icons:
      fill-icon:
        material: BLACK_STAINED_GLASS_PANE
        display-name: '&r'
        amount: 1
        slot: 36-44 #36,44
      team-size:
        material: PLAYER_HEAD
        display-name: '&9Team Size'
        amount: 1
        slot: 10
        lore:
          - '&7'
          - '&7Currently: &f{team-size}'
          - '&7'
          - '&7Member amount of a team.'
          - '&7'
          - '&c&lWARNING: &cChange of this'
          - '&csetting, resets all teams.'
          - '&7'
          - '&eLeft click to increase'
          - '&eRight click to decrease'
      team-amount:
        material: PLAYER_HEAD
        display-name: '&9Team Amount'
        amount: 1
        slot: 11
        lore:
          - '&7'
          - '&7Currently: &f{team-amount}'
          - '&7'
          - '&7Amount of teams in game.'
          - '&7'
          - '&c&lWARNING: &cChange of this'
          - '&csetting, resets all teams.'
          - '&7'
          - '&eLeft click to increase'
          - '&eRight click to decrease'
      invites:
        material: WRITABLE_BOOK
        display-name: '&9Invited Players'
        amount: 1
        slot: 12
        lore:
          - '&7'
          - '&7Pending Invites: {invited-players}'
          - '&7Players: {total-players}'
          - '&7'
          - '&7Invite a player to challenge'
          - '&7him.'
          - '&7'
          - '&eClick to open menu'

      rules:
        material: COMPARATOR
        display-name: '&9Rules'
        amount: 1
        slot: 13
        lore:
          - '&7'
          - '&7Game rules of game.'
          - '&7'
          - '&eClick to open gui'
      round-amount:
        material: STONE
        display-name: '&9Round Amount'
        amount: 1
        slot: 14
        lore:
          - '&7'
          - '&7Currently: &f{round-amount}'
          - '&7'
          - '&7How many rounds will the'
          - '&7game last?'
          - '&7'
          - '&85 round needs 3 win.'
          - '&7'
          - '&eLeft click to increase'
          - '&eRight click to decrease'
      kit:
        material: IRON_CHESTPLATE
        display-name: '&9Kit'
        amount: 1
        slot: 15
        lore:
          - '&7'
          - '&7Currently: &f{kit}'
          - '&7'
          - '&eClick to choose kit.'
      bet:
        material: EMERALD
        display-name: '&9Bet'
        amount: 1
        slot: 16
        lore:
          - '&7'
          - '&7Currently: &6{bet}'
          - '&7'
          - '&eClick to specify bet.'
      game-time:
        material: CLOCK
        display-name: '&9Game Time'
        amount: 1
        slot: 17
        lore:
          - '&7'
          - '&7Currently: &a{game-timer}'
          - '&7'
          - '&7Time out time of game.'
          - '&7'
          - '&eLeft click to increase'
          - '&eRight click to decrease'
      manage-teams:
        material: PAINTING
        display-name: '&9Manage Teams'
        amount: 1
        slot: 18
        lore:
          - '&7'
          - '&7Manage members of teams.'
          - '&7'
          - '&eClick to increase'
      start-game:
        material: EMERALD_BLOCK
        display-name: '&9Start Game!'
        amount: 1
        slot: 31
        lore:
          - '&7'
          - '&eClick to start duel game.'