name: BlokDuels
main: mc.obliviate.blokduels.BlokDuels
author: Mr_Obliviate
description: Duel plugin codded for Blok Dunyasi!
version: 2.2
api-version: 1.13
softdepend:
  - Multiverse-Core
  - TitleManager
  - TAB
commands:
  duelarenas:
  duel:
  dueladmin: