name: BlokDuels
main: mc.obliviate.blokduels.BlokDuels
author: Mr_Obliviate
description: Duel plugin codded for Blok Dunyasi!
version: 2.0-build134
softdepend:
  - Multiverse-Core
  - TitleManager
  - TAB
commands:
  duelarenas:
  duel:
  dueladmin: