name: BlokDuels
main: mc.obliviate.blokduels.bukkit.BlokDuels
author: Mr_Obliviate
description: Duel plugin codded for Blok Dunyasi!
version: 1.0.0
softdepend:
  - Multiverse-Core
  - TitleManager
  - TAB
commands:
  duelsetup:
  duelarenas:
  duel:
  duelkitsave: