#
# Official wiki: https://mrobliviate.gitbook.io/masterduels-wiki-1/
# Developer Contact: https://www.spigotmc.org/conversations/add?to=_Obliviate_
#
# MasterDuels coded by Mr_Obliviate
#

delay-end-duel-after-player-kill: 20 #in seconds
invite-timeout: 120 #in seconds

arena-regeneration:
  # SMART - removes only placed blocks, liquids, and formed blocks(blocks created when lava touched water)
  # ROLLBACKCORE (COMING SOON) - regenerates all blocks in the arena region (https://www.spigotmc.org/resources/rollbackcore-1-4-7-1-17-1.18517/)
  # SLIMEWORLD (COMING SOON) - regenerates the world completely (https://www.spigotmc.org/resources/advanced-slimeworldmanager.87209/)
  regenerate-mode: SMART
  remove-entities: true #removes DROPPED ITEMS and PROJECTILES that are in the arena region.

# if set true, players can break only placed blocks by a player (and formed blocks).
prevent-break-non-placed-blocks: true

# if set true, teleports the player to arena area(1. team's 1. position) when they break/place block
# to out of arena cuboid. Do not set it true if you didn't set arena cuboids correctly.
teleport-back-when-arena-cuboid-violated: false

# if set true, MasterDuels will change Bukkit world configurations of all worlds of arenas. This includes
# the game rules of the world. We recommend this if your duel arenas are in a different world
# from other worlds you're using for another thing.
optimize-duel-worlds: false

# if set true, MasterDuels will not reset and backup inventory. (so this is means you're disabling kits)
# also, when a player dies in a duel, their items will drop. Do not change this option during server work.
use-player-inventories: false

# SERVER_WIDE - sends game end message to all players on the server
# SPECTATORS_AND_MEMBERS - sends game end message to all players in the duel game
# DISABLED - no message send
game-end-broadcast-mode: 'SERVER_WIDE'

top:
  top-wins:
    calculation-limit: 10
execute-console-commands:
  when-duel-ended:
  #- this_command_will_be_executed_by_console_when_a_duel_game_ended
# placeholders are unsupported yet.

executable-commands-by-player:
  PLAYING:
  #- this_command_is_executable_in_battle
  ROUND_STARTING:
  #- this_command_is_executable_before_game_start
  MATCH_ENDING:
  #- this_command_is_executable_after_victim_dead
  #- this_command_is_executable_after_victim_dead_too
  #empty lists means all commands should be blocked.

duel-game-lock:
  lock-duration: 5 #in seconds
  teleport-frequency: 5 #teleport amount per second
  notify-actions:
    first-action:
      remaining-time: 5 #remaining lock time in seconds
      sound: NOTE_BASS
      title:
        subtitle: '&a&l5'
        fadein: 5
        fadeout: 0
    second-action:
      remaining-time: 4
      sound: NOTE_BASS
      title:
        title: ''
        subtitle: '&a&l4'
        fadein: 0
    third-action:
      remaining-time: 3 #remaining lock time in seconds
      sound: NOTE_BASS
      title:
        title: ''
        subtitle: '&a&l3'
        fadein: 0
    fourth-action:
      remaining-time: 2
      sound: NOTE_BASS
      title:
        title: ''
        subtitle: '&a&l2'
        fadein: 0
    fiveth-action:
      remaining-time: 1
      sound: NOTE_BASS
      title:
        subtitle: '&a&l1'
        fadein: 5
        fadeout: 0
    sixth-action:
      remaining-time: 0
      sound: NOTE_PIANO
      title:
        title: '&a&lGO'
        fadein: 5
        fadeout: 0
      #chat: '&aGood luck!'
      #action-bar: '&aGame is started'

#{timer} = 13:59
#{time} = 13 minutes 59 seconds
#You can translate time format from message.yml time-format
scoreboards: #Requires TitleManager plugin
  enabled: true
  PLAYING:
    title: '&e&lDUELS'
    live-opponent-format: '&a{name} &c{health}❤'
    dead-opponent-format: '&a{name} &cDEAD'
    quit-opponent-format: '&a{name} &cQUIT'
    lines:
      - '&fRound: &e#{round}'
      - '&fMap: &e{map}'
      - ''
      - '&fRemaining Time:'
      - ' &a{timer}'
      - ''
      - '{+opponents}' # placeholders that is starts with '+', will clone as line for each opponent of player
      - ''
      - '&ewww.yourserver.net'
  ROUND_STARTING:
    title: '&e&lDUELS'
    live-opponent-format: '&a{name} &c{health}❤'
    dead-opponent-format: '&a{name} &cDEAD'
    quit-opponent-format: '&a{name} &cQUIT'
    lines:
      - '&fRound: &e#{round}'
      - '&fMap: &e{map}'
      - ''
      - '&fStarting: &a{timer}'
      - ''
      - '&ewww.yourserver.net'
  MATCH_ENDING:
    title: '&e&lDUELS'
    live-opponent-format: '&a{name} &c{health}❤'
    dead-opponent-format: '&a{name} &cDEAD'
    quit-opponent-format: '&a{name} &cQUIT'
    lines:
      - '&fRound: &e#{round}'
      - '&fMap: &e{map}'
      - ''
      - '&fArena Closing: '
      - '&c{timer}'
      - ''
      - '{+opponents}'
      - ''
      - '&ewww.yourserver.net'

boss-bars:
  enabled: true
  # MasterDuels can use TAB's boss bar API or its own boss bar manager.
  # Boss bar manager of MasterDuels doesn't support 1.8 but TAB's API does.
  # TAB -> uses TAB's Boss Bars
  # INTERNAL -> uses MasterDuels's Boss Bars
  # AUTO -> If the server version is 1.8 uses TAB boss bars otherwise uses internal boss bars.
  mode: AUTO
  in-battle: 'Remaining Time: {time}' #also, you can use {timer} placeholder
  arena-closing: 'Arena Closing in: {time}'
game-history:
  enabled: true
  max-amount-of-histories-in-storage: 50
  cache-refresh: 1200 #in ticks
  gui:
    title: 'Duel History'
    solo-games-icon:
      material: PAPER
      display-name: '&dGame Duration: &7{time}'
      lore:
        - ''
        - '&a{winner} &8⚔ &c{loser}'
        - ''
        - '&8Game played at: {played-date}'
    non-solo-games-icon:
      winners-format: ' &a{winner}!'
      losers-format: ' &c{loser}'
      material: PAPER
      display-name: '&dGame Duration: &7{time}'
      lore:
        - ''
        - '&aWinners:'
        - ' {+winners}'
        - ''
        - '&cLosers:'
        - ' {+losers}'
        - ''
        - '&8Game played at: {played-date}'

duel-arenas-gui:
  enabled: true
  #You need 'masterduels.see-non-playing-games' permission to see 'disabled' and 'empty' arenas.
  title: 'Duel Arenas'
  size: 6
  page-slots: 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53
  icons:
    STARTING:
      material: YELLOW_WOOL
      display-name: '&dArena: #{arena}'
      lore:
        - ''
        - '&7State: &eStarting...'
        - '&7Players: &b{players}'
        - '&7Mode: &b{mode}'
        - ''
        - '&eClick to spectate game!'
    PLAYING:
      material: RED_WOOL
      display-name: '&dArena: #{arena}'
      lore:
        - ''
        - '&7State: &cPlaying'
        - '&7Players: &b{players}'
        - '&7Mode: &b{mode}'
        - ''
        - '&eClick to spectate game!'
    ENDING:
      material: YELLOW_WOOL
      display-name: '&dArena: #{arena}'
      lore:
        - ''
        - '&7State: &eEnding'
        - '&7Players: &b{players}'
        - '&7Mode: &b{mode}'
        - ''
        - '&eClick to spectate game!'
    EMPTY:
      material: LIME_WOOL
      display-name: '&dArena: #{arena}'
      lore:
        - ''
        - '&7State: &aAvailable'
        - '&7Map: &9{map}'
        - ''
    DISABLED:
      material: REDSTONE_BLOCK
      display-name: '&dArena: #{arena}'
      lore:
        - '&cThis arena currently'
        - '&cdisabled by administrators.'
        - ''
    UNKNOWN:
      material: BEDROCK
      display-name: '&dArena: #{arena}'
      lore:
        - ''
        - '&4Error'
        - ''

duel-creator:
  data-limits:
    max-team-size: 8
    min-team-size: 1
    max-team-amount: 2
    min-team-amount: 10
    max-rounds: 5
    min-rounds: 1
    max-game-time: 600 #in seconds
    min-game-time: 60 #in seconds
    allowed-kits: #these kits are selectable
      - '*'
    allowed-game-rules: #these game rules are setable
      - '*'
      #- NO_BOW
  gui:
    title: 'Duel Creator {mode} &c&lBETA'
    size: 6
    icons:
      fill-icon: #dysfunctional icon
        material: BLACK_STAINED_GLASS_PANE
        slot: 45-53
        display-name: '&r'
      team-size:
        material: PLAYER_HEAD
        slot: 11
        display-name: '&9Team Size'
        lore:
          - '&7'
          - '&7Currently: &f{team-size}'
          - '&7'
          - '&7Member amount of a team.'
          - '&7'
          - '&c&lWARNING: &cChange of this'
          - '&csetting, resets all teams.'
          - '&7'
          - '&eLeft click to increase'
          - '&eRight click to decrease'
      team-amount:
        material: PLAYER_HEAD
        slot: 12
        display-name: '&9Team Amount'
        lore:
          - '&7'
          - '&7Currently: &f{team-amount}'
          - '&7'
          - '&7Amount of teams in game.'
          - '&7'
          - '&c&lWARNING: &cChange of this'
          - '&csetting, resets all teams.'
          - '&7'
          - '&eLeft click to increase'
          - '&eRight click to decrease'
      invites:
        material: WRITABLE_BOOK
        slot: 13
        display-name: '&9Invited Players'
        lore:
          - '&7'
          - '&7Pending Invites: {invited-players}'
          - '&7Players: {total-players}'
          - '&7'
          - '&7Invite a player to challenge'
          - '&7him.'
          - '&7'
          - '&eClick to open menu'
      rules:
        material: COMPARATOR
        slot: 14
        display-name: '&9Rules'
        lore:
          - '&7'
          - '&7Game rules of game.'
          - '&7'
          - '&eClick to open gui'
      round-amount:
        material: LADDER
        slot: 15
        display-name: '&9Round Amount'
        lore:
          - '&7'
          - '&7Currently: &f{round-amount}'
          - '&7'
          - '&7How many rounds will the'
          - '&7game last?'
          - '&7'
          - '&85 round needs 3 win.'
          - '&7'
          - '&eLeft click to increase'
          - '&eRight click to decrease'
      kit:
        material: IRON_CHESTPLATE
        slot: 20
        display-name: '&9Kit'
        lore:
          - '&7'
          - '&7Currently: &f{kit}'
          - '&7'
          - '&eClick to choose kit.'
      game-time:
        material: CLOCK
        slot: 21
        display-name: '&9Game Time'
        lore:
          - '&7'
          - '&7Currently: &a{game-timer}'
          - '&7'
          - '&7Time out time of game.'
          - '&7'
          - '&eLeft click to increase'
          - '&eRight click to decrease'
      manage-teams:
        material: PAINTING
        slot: 22
        display-name: '&9Manage Teams'
        lore:
          - '&7'
          - '&7Manage members of teams.'
          - '&7'
          - '&eClick to increase'
      start-game:
        material: EMERALD_BLOCK
        slot: 49
        display-name: '&9Start Game!'
        lore:
          - '&7'
          - '&eClick to start duel game.'
  manage-teams-gui:
    title: Manage Teams
    #the size of gui is dynamic
    icons:
      fill-icon:
        material: BLACK_STAINED_GLASS_PANE
        slot: 0-8
        display-name: '&r'
      empty-player-slot:
        material: BARRIER
        display-name: '&cEmpty!'
        lore:
          - ''
          - '&7Put a player''s head here'
          - '&7to add him to team.'
      player-slot:
        material: PLAYER_HEAD
        display-name: '&e{player}'
      team-slot:
        dynamic-materials:
          - RED_STAINED_GLASS
          - BLUE_STAINED_GLASS
          - YELLOW_STAINED_GLASS
          - LIME_STAINED_GLASS
          - PURPLE_STAINED_GLASS
          - CYAN_STAINED_GLASS
          - ORANGE_STAINED_GLASS
          - PINK_STAINED_GLASS
          - LIGHT_BLUE_STAINED_GLASS
          - GREEN_STAINED_GLASS
        display-name: '&f{team-no}. team'
        lore:
          - '&7({team-players-amount}&8/&7{team-size})'
      back:
        material: ARROW
        slot: 0
        display-name: '&cBack'
  game-rules-gui:
    title: 'Game Rules'
    size: 3
    icons:
      fill-icon:
        material: BLACK_STAINED_GLASS_PANE
        slot: 0-8
        display-name: '&r'
      back:
        material: ARROW
        slot: 0
        display-name: '&cBack'
  invites-gui:
    title: 'Pending Invites'
    size: 5
    icons:
      fill-icon:
        material: BLACK_STAINED_GLASS_PANE
        slot: 0-8
        display-name: '&r'
      back:
        material: ARROW
        slot: 0
        display-name: '&cBack'
      invite:
        material: WRITABLE_BOOK
        slot: 4
        display-name: '&aInvite a Player'
        lore:
          - ''
          - '&7Current Players: {players-amount}'
          - '&7Pending Invites: {pending-invites-amount}'
          - ''
          - '&eClick to invite a player!'

duel-queues:
  enabled: true