name: MasterDuels
main: mc.obliviate.masterduels.MasterDuels
author: Mr_Obliviate
description: Professional duel game plugin for professional servers.
version: 22.12.0
api-version: 1.13
softdepend:
  - Multiverse-Core
  - TAB
  - Vault
  - AdvancedReplay
commands:
  duel:
    aliases:
      - masterduels
  dueladmin:
permissions:
  masterduels.duelcreator.set.teamsize:
    default: true
    description: allows changing the team size
  masterduels.duelcreator.set.teamamount:
    default: true
    description: allows changing the team amount
  masterduels.duelcreator.set.rules:
    default: true
    description: allows ruling creator
  masterduels.duelcreator.set.roundamount:
    default: true
    description: allows changing the round amount
  masterduels.duelcreator.set.teammanager:
    default: true
    description: allows managing teams
  masterduels.duelcreator.set.kit:
    default: true
    description: allows setting kits
  masterduels.duelcreator.set.finishtime:
    default: true
    description: allows changing the duration of match
