name: MasterDuels
main: mc.obliviate.masterduels.MasterDuels
author: Mr_Obliviate
description: Professional duel game plugin for professional servers.
version: ${project.artifactId}-${project.version}.${buildNumber}
api-version: 1.13
softdepend:
  - Multiverse-Core
  - TitleManager
  - TAB
  - Vault
commands:
  duel:
  dueladmin: